package com.example.demonslayer.model

object FakeHeroDataSource {
    val dummyHeroes = listOf(
        Hero(1,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/f/f9/Tanjiro_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20191224040903",
            "Tanjiro Kamado",
            "165 cm",
            "61 kg",
            "Male", false),
        Hero(2,
        "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/3/3b/Nezuko_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20191129165545",
            "Nezuko Kamado",
            "153 cm",
            "45 kg",
            "Female", false),
        Hero(3,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/f/f8/Mitsuri_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20230410185921",
            "Mitsuri Kanroji",
            "167 cm",
            "56 kg",
            "Female", false),
        Hero(4,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/9/9e/Muichiro_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20191125200456",
            "Muichiro Tokito",
            "160 cm",
            "56 kg",
            "Male", false),
        Hero(5,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/2/2e/Genya_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20191125204519",
            "Genya Shinazugawa",
            "180 cm",
            "76 kg",
            "Male", false),
        Hero(6,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/3/3c/Kotetsu_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20230410074444",
            "Kotetsu",
            "170 cm",
            "60 kg",
            "Male", false),
        Hero(7,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/d/d9/Hotaru_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20191129174154",
            "Hotaru Haganezuka",
            "180 cm",
            "70 kg",
            "Male", false),
        Hero(8,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/3/3e/Kozo_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20191129174309",
            "Kozo Kanamori",
            "165 cm",
            "50 kg",
            "Male", false),
        Hero(9,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/a/a6/Tecchin_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20230410035338",
            "Tecchin Tecchikawahara",
            "182 cm",
            "78 kg",
            "Male", false),
        Hero(10,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/b/b9/Yoriichi_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20230410161550",
            "Yoriichi Tsugikuni",
            "165 cm",
            "56 kg",
            "Male", false),
        Hero(11,
            "https://static.wikia.nocookie.net/kimetsu-no-yaiba/images/c/c2/Hantengu_Anime_Profile.png/revision/latest/scale-to-width-down/98?cb=20230410123544",
            "Hantengu",
            "167 cm",
            "50 kg",
            "Male", false),

    )
}